apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketlens-stream-processor
  namespace: marketlens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-processor
  template:
    metadata:
      labels:
        app: stream-processor
    spec:
      serviceAccountName: marketlens-sa
      containers:
      - name: processor
        image: ghcr.io/marketlens-ai-platform/marketlens-stream-processor:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "marketlens-kafka:9092"
        - name: S3_BUCKET
          value: "marketlens-raw-ingestion-v110"
